apiVersion: v1
kind: Pod

metadata:
  name: pod4

spec:
  volumes:
  - name: vol1
    configMap: 
      name: cm3
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: vol1
          mountPath: /config_file1.txt
