apiVersion: apps/v1
kind: Deployment

metadata:
  name: dep1

spec:
  replicas: 2
  selector:
    matchLabels:
      red: green
  template:
    metadata:
      labels:
        red: green
    spec:
      nodeSelector: 
        disk: ssd
      containers:
      - name: nginx
        image: nginx:1.14.2

