apiVersion: apps/v1
kind: Deployment

metadata:
  name: deplgreen

spec:
  replicas: 3
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - name: cont44
        image: nginx:1.22
