apiVersion: v1 
kind: Pod 

metadata:
  name: pod3


spec:
  containers:
    - name: cont1
      image: nginx 
      volumeMounts:
        - name: vol1
          mountPath: /nivin
  volumes:
    - name: vol1
      hostPath:
        path: /data
