apiVersion: v1
kind: Pod


metadata:
  name: pod3


spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: vol2
          mountPath: /abc
  volumes:
    - name: vol2
      nfs:
        server: 172.31.43.70 
        path: /datadir
