apiVersion: v1
kind: Pod

metadata: 
  name: pod32

spec:
  containers: 
    - name: cont1
      image: httpd
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 200Mi

       

