apiVersion: v1
kind: Pod


metadata:
  name: pod2


spec:
  containers:
    - name: cont2
      image: httpd
      volumeMounts:
        - name: vol1
          mountPath: /alex
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: pvc1
