apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 1
  selector:
    app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: cont2
        image: httpd
