apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  selector:
    matchLabels:
      env: prod 
  serviceName: svc45
  replicas: 3 
  template:
    metadata:
      labels:
         env: prod 
    spec:
      containers:
      - name: cont1
        image: httpd
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
