apiVersion: v1
kind: Service

metadata:
  name: svc45

spec:
  clusterIP: None
  type: ClusterIP
  selector: 
    env: prod
  ports: 
    - name: port
      port: 8080
      targetPort: 80
      protocol: TCP




