apiVersion: v1
kind: Service

metadata:
  name: svc2

spec:
  type: NodePort
  selector: 
    env: prod
  ports: 
    - name: port
      port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30080




