apiVersion: v1
kind: Service

metadata:
  name: svcbluegreen

spec:
  type: NodePort
  selector: 
    app: newapp
  ports: 
    - name: port
      port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30080




