---
apiVersion: v1
kind: Pod

metadata:
  name: pod6

spec:
volumes:
  - name: vol1

  containers:
    - name: cont1
      image: nginx
      env:
        - name: USERNAME
          valueFrom: 
            configMapKeyRef:
              name: cm1
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef: 
              name: sec1
              key: pass
