---
apiVersion: v1
kind: Pod
metadata:
  name: pod4

spec:
  volumes:
    - name: vol1
      emptyDir: {}
  containers:
    - name: cont1
      image: httpd
      volumeMounts:
        - name: vol1
          mountPath: /test
    - name: cont2
      image: redis
      volumeMounts:
        - name: vol1
          mountPath: /nivin

