---
apiVersion: v1
kind: Pod

metadata:
  name: pod6

spec:
  containers:
    - name: cont1
      image: nginx
      env:
        - name: USERNAME
          value: testuser
        - name: PASSWORD
          value: e1234
