apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds1

spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: cont2
        image: httpd
