---
apiVersion: v1
kind: Pod
metadata:
  name: pod3

spec:
  volumes:
    - name: vol1
      gitRepo:
        repository: https://github.com/vsaini44/KubernetesRepo.git
        revision: master
        directory: .
  containers:
    - name: cont1
      image: httpd
      volumeMounts:
        - name: vol1
          mountPath: /datadir

